# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{km-psych}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Aaron Patterson", "John Barnette"]
  s.date = %q{2010-11-29}
  s.description = %q{Psych is a YAML parser and emitter}
  s.email = %q{aaronp@rubyforge.org, jbarnette@rubyforge.org}
  s.extensions = ["ext/psych/extconf.rb"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "ext/psych/emitter.c",
    "ext/psych/emitter.h",
    "ext/psych/extconf.rb",
    "ext/psych/parser.c",
    "ext/psych/parser.h",
    "ext/psych/psych.c",
    "ext/psych/psych.h",
    "ext/psych/to_ruby.c",
    "ext/psych/to_ruby.h",
    "ext/psych/yaml_tree.c",
    "ext/psych/yaml_tree.h",
    "lib/km-psych.rb",
    "lib/psych/coder.rb",
    "lib/psych/core_ext.rb",
    "lib/psych/deprecated.rb",
    "lib/psych/handler.rb",
    "lib/psych/json.rb",
    "lib/psych/json/stream.rb",
    "lib/psych/json/tree_builder.rb",
    "lib/psych/nodes.rb",
    "lib/psych/nodes/alias.rb",
    "lib/psych/nodes/document.rb",
    "lib/psych/nodes/mapping.rb",
    "lib/psych/nodes/node.rb",
    "lib/psych/nodes/scalar.rb",
    "lib/psych/nodes/sequence.rb",
    "lib/psych/nodes/stream.rb",
    "lib/psych/omap.rb",
    "lib/psych/parser.rb",
    "lib/psych/scalar_scanner.rb",
    "lib/psych/set.rb",
    "lib/psych/stream.rb",
    "lib/psych/tree_builder.rb",
    "lib/psych/visitors.rb",
    "lib/psych/visitors/emitter.rb",
    "lib/psych/visitors/json_tree.rb",
    "lib/psych/visitors/to_ruby.rb",
    "lib/psych/visitors/visitor.rb",
    "lib/psych/visitors/yaml_tree.rb"
  ]
  s.homepage = %q{http://github.com/tenderlove/psych}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Port of Psych to use Jeweler as gem release manager}
  s.test_files = [
    "test/psych/helper.rb",
    "test/psych/json/test_stream.rb",
    "test/psych/test_alias_and_anchor.rb",
    "test/psych/test_array.rb",
    "test/psych/test_boolean.rb",
    "test/psych/test_class.rb",
    "test/psych/test_coder.rb",
    "test/psych/test_date_time.rb",
    "test/psych/test_deprecated.rb",
    "test/psych/test_document.rb",
    "test/psych/test_emitter.rb",
    "test/psych/test_encoding.rb",
    "test/psych/test_engine_manager.rb",
    "test/psych/test_exception.rb",
    "test/psych/test_hash.rb",
    "test/psych/test_json_tree.rb",
    "test/psych/test_null.rb",
    "test/psych/test_object.rb",
    "test/psych/test_omap.rb",
    "test/psych/test_parser.rb",
    "test/psych/test_psych.rb",
    "test/psych/test_scalar.rb",
    "test/psych/test_scalar_scanner.rb",
    "test/psych/test_serialize_subclasses.rb",
    "test/psych/test_set.rb",
    "test/psych/test_stream.rb",
    "test/psych/test_string.rb",
    "test/psych/test_struct.rb",
    "test/psych/test_symbol.rb",
    "test/psych/test_to_yaml_properties.rb",
    "test/psych/test_tree_builder.rb",
    "test/psych/test_yaml.rb",
    "test/psych/visitors/test_emitter.rb",
    "test/psych/visitors/test_to_ruby.rb",
    "test/psych/visitors/test_yaml_tree.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<test-unit>, [">= 2.0.1"])
    else
      s.add_dependency(%q<test-unit>, [">= 2.0.1"])
    end
  else
    s.add_dependency(%q<test-unit>, [">= 2.0.1"])
  end
end

